# Generated by Django 5.2.5 on 2025-10-08 23:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='thumb_series')),
                ('descricao', models.TextField(max_length=500)),
                ('categoria', models.CharField(choices=[('TERROR', 'Terror'), ('SUSPENSE', 'Suspense'), ('COMEDIA', 'Comédia'), ('ROMANCE', 'Romance'), ('ACAO', 'Ação'), ('AVENTURA', 'Aventura'), ('FICCAO_CIENTIFICA', 'Ficção Científica'), ('FANTASIA', 'Fantasia'), ('DRAMA', 'Drama'), ('MISTERIO', 'Mistério'), ('ANIMACAO', 'Animação'), ('ANIME', 'Anime'), ('DOCUMENTARIO', 'Documentário'), ('BIOGRAFIA', 'Biografia'), ('MUSICAL', 'Musical'), ('GUERRA', 'Guerra'), ('CRIME', 'Crime'), ('FAMILIA', 'Família'), ('HISTORIA', 'História'), ('FAROESTE', 'Faroeste'), ('OUTROS', 'Outros')], max_length=100)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('video', models.URLField()),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='serie.serie')),
            ],
        ),
    ]
