# Generated by Django 5.2.5 on 2025-09-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('TERROR', 'Terror'), ('SUSPENSE', 'Suspense'), ('COMEDIA', 'Comédia'), ('OUTROS', 'Outros')], max_length=15),
        ),
    ]
