# Generated by Django 5.2.5 on 2025-09-11 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_alter_filme_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='tituto',
            new_name='titulo',
        ),
    ]
