# Generated by Django 5.2.5 on 2025-10-01 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0004_serie_alter_filme_categoria_episodio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodio',
            old_name='filme',
            new_name='serie',
        ),
    ]
