# Generated by Django 5.2.5 on 2025-10-02 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0005_rename_filme_episodio_serie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Episodio',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
