# Generated by Django 5.2.5 on 2025-10-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0006_delete_episodio_delete_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
